import { Routes } from '@angular/router';
import { ProductionLayoutComponent } from '../../../layout/production-layout/production-layout.component';
import { productionHomeRedirectGuard, productionRoleGuard } from '../infrastructure/production-role.guard';

export const PRODUCTION_ROUTES: Routes = [
  {
    path: '',
    component: ProductionLayoutComponent,
    children: [
      // '' n'a plus de destination fixe : chaque rôle est redirigé vers SON tableau de bord.
      { path: '', pathMatch: 'full', canActivate: [productionHomeRedirectGuard], children: [] },
      { path: 'dashboard', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/dashboard/production-dashboard.component').then(m => m.ProductionDashboardComponent) },
      { path: 'plan', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/plan/production-plan.component').then(m => m.ProductionPlanComponent) },
      { path: 'chef-production/bons-commande', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/bons-commande/cp-bons-commande.component').then(m => m.CpBonsCommandeComponent) },
      { path: 'chef-production/validation-bc', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/validation-bc/cp-validation-bc.component').then(m => m.CpValidationBcComponent) },
      { path: 'chef-production/planification', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/planification/cp-planification.component').then(m => m.CpPlanificationComponent) },
      { path: 'chef-production/suivi-global', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/suivi-global/cp-suivi-global.component').then(m => m.CpSuiviGlobalComponent) },
      { path: 'chef-production/coordination', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/coordination/cp-coordination.component').then(m => m.CpCoordinationComponent) },
      { path: 'chef-production/ressources', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/ressources/cp-ressources.component').then(m => m.CpRessourcesComponent) },
      { path: 'chef-production/performances', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/performances/cp-performances.component').then(m => m.CpPerformancesComponent) },
      { path: 'chef-production/statistiques', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/statistiques/cp-statistiques.component').then(m => m.CpStatistiquesComponent) },
      { path: 'chef-production/alertes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/alertes/cp-alertes.component').then(m => m.CpAlertesComponent) },
      { path: 'chef-production/historique', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/historique/cp-historique.component').then(m => m.CpHistoriqueComponent) },
      { path: 'chef-production/telechargements', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-production/telechargements/cp-telechargements.component').then(m => m.CpTelechargementsComponent) },
      { path: 'saisie', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/saisie/production-saisie.component').then(m => m.ProductionSaisieComponent) },
      { path: 'chef-machiniste/dashboard', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/dashboard/cm-dashboard.component').then(m => m.CmDashboardComponent) },
      { path: 'chef-machiniste/plans', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/plans/cm-plans.component').then(m => m.CmPlansComponent) },
      { path: 'chef-machiniste/objectifs', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/objectifs/cm-objectifs.component').then(m => m.CmObjectifsComponent) },
      { path: 'chef-machiniste/realisations', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/realisations/cm-realisations.component').then(m => m.CmRealisationsComponent) },
      { path: 'chef-machiniste/indicateurs', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/indicateurs/cm-indicateurs.component').then(m => m.CmIndicateursComponent) },
      { path: 'chef-machiniste/suivi', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/suivi/cm-suivi.component').then(m => m.CmSuiviComponent) },
      { path: 'chef-machiniste/performances', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/performances/cm-performances.component').then(m => m.CmPerformancesComponent) },
      { path: 'chef-machiniste/classements', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/classements/cm-classements.component').then(m => m.CmClassementsComponent) },
      { path: 'chef-machiniste/statistiques', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/statistiques/cm-statistiques.component').then(m => m.CmStatistiquesComponent) },
      { path: 'chef-machiniste/rapports', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/chef-machiniste/rapports/cm-rapports.component').then(m => m.CmRapportsComponent) },
      { path: 'agent-doseur/dashboard', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/dashboard/ad-dashboard.component').then(m => m.AdDashboardComponent) },
      { path: 'agent-doseur/plans', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/plans/ad-plans.component').then(m => m.AdPlansComponent) },
      { path: 'agent-doseur/sessions', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/session-jour/ad-session-jour.component').then(m => m.AdSessionJourComponent) },
      { path: 'agent-doseur/dosage', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/dosage/ad-dosage.component').then(m => m.AdDosageComponent) },
      { path: 'agent-doseur/melange', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/melange/ad-melange.component').then(m => m.AdMelangeComponent) },
      { path: 'agent-doseur/machines', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/machines/ad-machines.component').then(m => m.AdMachinesComponent) },
      { path: 'agent-doseur/futs', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/futs/ad-futs.component').then(m => m.AdFutsComponent) },
      { path: 'agent-doseur/predictions', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/predictions/ad-predictions.component').then(m => m.AdPredictionsComponent) },
      { path: 'agent-doseur/suivi', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/suivi/ad-suivi.component').then(m => m.AdSuiviComponent) },
      { path: 'agent-doseur/statistiques', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/statistiques/ad-statistiques.component').then(m => m.AdStatistiquesComponent) },
      { path: 'agent-doseur/registre', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/registre/ad-registre.component').then(m => m.AdRegistreComponent) },
      { path: 'agent-doseur/documents', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/agent-doseur/documents/ad-documents.component').then(m => m.AdDocumentsComponent) },
      { path: 'lots', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/lots/production-lots.component').then(m => m.ProductionLotsComponent) },
      { path: 'declaration-lot', canActivate: [productionRoleGuard], loadComponent: () => import('../../stock/presentation/pages/declaration-lot/declaration-lot.component').then(m => m.DeclarationLotComponent) },
      { path: 'responsable-salle/dashboard', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/dashboard/rs-dashboard.component').then(m => m.RsDashboardComponent) },
      { path: 'responsable-salle/bons-commande', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/bons-commande/rs-bons-commande.component').then(m => m.RsBonsCommandeComponent) },
      { path: 'responsable-salle/plans-pph', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/plans-pph/rs-plans-pph.component').then(m => m.RsPlansPphComponent) },
      { path: 'responsable-salle/ajustement-plan', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/ajustement-plan/rs-ajustement-plan.component').then(m => m.RsAjustementPlanComponent) },
      { path: 'responsable-salle/affectation-employes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/affectation-employes/rs-affectation-employes.component').then(m => m.RsAffectationEmployesComponent) },
      { path: 'responsable-salle/referentiel-postes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/referentiel-postes/rs-referentiel-postes.component').then(m => m.RsReferentielPostesComponent) },
      { path: 'responsable-salle/planning-journalier', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/planning-journalier/rs-planning-journalier.component').then(m => m.RsPlanningJournalierComponent) },
      { path: 'responsable-salle/realisations-poste', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/realisations-poste/rs-realisations-poste.component').then(m => m.RsRealisationsPosteComponent) },
      { path: 'responsable-salle/production-individuelle', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/production-individuelle/rs-production-individuelle.component').then(m => m.RsProductionIndividuelleComponent) },
      { path: 'responsable-salle/comparaison-doseur', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/comparaison-doseur/rs-comparaison-doseur.component').then(m => m.RsComparaisonDoseurComponent) },
      { path: 'responsable-salle/performances-postes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/performances-postes/rs-performances-postes.component').then(m => m.RsPerformancesPostesComponent) },
      { path: 'responsable-salle/classement-employes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/classement-employes/rs-classement-employes.component').then(m => m.RsClassementEmployesComponent) },
      { path: 'responsable-salle/registre-journalier', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/registre-journalier/rs-registre-journalier.component').then(m => m.RsRegistreJournalierComponent) },
      { path: 'responsable-salle/fiche-info-produit', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/fiche-info-produit/rs-fiche-info-produit.component').then(m => m.RsFicheInfoProduitComponent) },
      { path: 'responsable-salle/statistiques', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/statistiques/rs-statistiques.component').then(m => m.RsStatistiquesComponent) },
      { path: 'responsable-salle/telechargements', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/responsable-salle/telechargements/rs-telechargements.component').then(m => m.RsTelechargementsComponent) },
      { path: 'employes', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/employes/production-employes.component').then(m => m.ProductionEmployesComponent) },
      { path: 'besoins', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/besoins/production-besoins.component').then(m => m.ProductionBesoinsComponent) },
      { path: 'rapports', canActivate: [productionRoleGuard], loadComponent: () => import('./pages/rapports/production-rapports.component').then(m => m.ProductionRapportsComponent) },
    ]
  }
];
